### ISSUE TITLE
Migration script won't work with Askar, as it uses the wallet export

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#1318]
Not sure what to do here. Maybe we can do an sql dump and export that? We would still need to support that in Askar though, otherwise we need an sql client

**Comment by swcurran** [comment]
Could you please provide more detail on this?

What does this block, and where do you expect the solution to come?

Askar’s export/import functionality is being expanded to match that of indy-sdk — does that help?

**Comment by genaris** [comment]
> Askar’s export/import functionality is being expanded to match that of indy-sdk — does that help?

Absolutely. I'm looking forward to get the new functionality regarding queries without categories so we can easily retrieve all records from the database and do a dump to JSON or any other convenient format that can allow us to properly manipulate and transform to other backends.

If this new feature of Askar is going to get ready soon, we can wait for it.

**Comment by swcurran** [comment]
@andrewwhitehead — I think you have this almost ready, right?  The handling of the release was holding it up, right?

**Comment by TimoGlastra** [comment]
Solved for SQLite by copying the database file. For Postgres we need to be able to query all records, or just make a dump of the postgres database itself.

**Comment by genaris** [comment]
This is getting a higher priority now, as in 8cc499d133f67be391a7956ac51f6078af78f69d the storage version was updated to 0.5, making any existing Askar wallet coming from 0.4 to execute migration script.

When running it in one of our applications using postgres DB backend, I found the unfortunate error:

```
2024-02-01 21:53:51.675 DEBUG /build/config/logger.js:61 Wallet '2060-cloud-agent-dev' opened with handle '1'
2024-02-01 21:53:51.688 INFO /build/config/logger.js:61 Agent storage is not up to date.
2024-02-01 21:53:51.690 INFO /build/config/logger.js:61 Starting update of agent storage with updateIdentifier 1706824431689
2024-02-01 21:53:51.699 INFO /build/config/logger.js:61 Starting update process. Total of 1 update(s) will be applied to update the agent storage from version 0.4 to version 0.5
2024-02-01 21:53:51.702 ERROR /build/config/logger.js:58 Error updating storage (updateIdentifier: 1706824431689) {
  cause: {
    name: 'WalletError',
    message: 'Export is only supported for SQLite backend',
    stack: 'WalletError: Export is only supported for SQLite backend\n' +
      '    at AskarWallet.export (/www/node_modules/@credo-ts/askar/build/wallet/AskarWallet.js:222:19)\n' +
      '    at WalletApi.export (/www/node_modules/@credo-ts/core/build/wallet/WalletApi.js:89:33)\n' +
      '    at UpdateAssistant.createBackup (/www/node_modules/@credo-ts/core/build/storage/migration/UpdateAssistant.js:168:39)\n' +
      '    at UpdateAssistant.update (/www/node_modules/@credo-ts/core/build/storage/migration/UpdateAssistant.js:96:24)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async CloudAgent.initialize (/www/node_modules/@credo-ts/core/build/agent/BaseAgent.js:106:13)\n' +
      '    at async CloudAgent.initialize (/www/node_modules/@credo-ts/core/build/agent/Agent.js:120:9)\n' +
      '    at async initCloudAgent (/www/build/agent/initCloudAgent.js:59:5)\n' +
      '    at async run (/www/build/index.js:13:9)'
  }
}
ERROR: StorageUpdateError: Error updating storage (updateIdentifier: 1706824431689): Export is only supported for SQLite backend
``` 

As now we are using `copyTo` method from Askar, I think it can be possible to export from postgres database (and even do a dump to sqlite), so there are big chances that this wallet backup procedure can work by just removing the line where the error is thrown. However we'll need to test it because the whole update process (which does wallet export + delete + import in case of an error) is originally meant for file system-based DBs and may have issues in a 'real' database.

I think that for this particular case it is OK to dump the backup to an sqlite file and then import it in case of error during migration. Not sure if this will be a good solution in long-term, thinking on cloud wallets with a massive amount of data (either mediators or multi-tenancy agents). I guess in those cases users may prefer to disable `autoUpdateStorageOnStartup` and run the update process manually to get more control.

**Comment by TimoGlastra** [comment]
I think we should maybe add a config option that indicates you have created a backup yourself. For postgres it makes sense if you create regular backups anyway, and e.g. with neon.tech (which we use for Paradym) we can go back to any point in time from the last X days because they use WAL to keep track of changes to the DB over time.

So i think we shouldn't support a backup strategy for non file based dbs

**Comment by TimoGlastra** [comment]
This has been adressed. New issues can focus on improveents / extensions
