### ISSUE TITLE
Improve agent configuration

### ISSUE THREAD

**Issue by jakubkoci** [openwallet-foundation/credo-ts#486]
As a Developer, I want to have access to config via `agent` instance, so that I can do that wherever I'm using `agent.` For example, I can use `label` when running two agent instances to distinguish between them in logs.

As a Developer, I want to group agent config to make clear how each part relate together and what modules are influenced by a specific group.

```js
const agentConfig = {
  endpoints: process.env.AGENT_ENDPOINTS?.split(','),
  label: process.env.AGENT_LABEL || '',
  wallet: {
    id: process.env.WALLET_NAME || '',
    key: process.env.WALLET_KEY || '',
    publicDidSeed: process.env.PUBLIC_DID_SEED || '',
  },
  connections: {
    autoAcceptConnections: true,
  },
  mediation: {
    autoAcceptMediationRequests: true,
  },
  ledger: {
    genesisPath: '',
    poolName: `pool-name`,
  },
  logger: new ConsoleLogger(LogLevel.debug),
}
```

This structure is just to demonstrate the idea, I'm not saying it should look exactly like that :)

As a Developer, I want to define a config in JSON file, so that the config will be more explicit and extracted outside of code.

**Comment by TimoGlastra** [comment]
I agree! I like the nesting of grouped attributes, and think it would be good to be able to access the agent config the agent instance. As it's all getters and read only properties it's not opening the gates for unwanted modifications.

One thing I was thinking about whether we can remove the redundancy from the nested properties. So instead of `autoAcceptConnections` all it `autoAccept` as it's under `connections` key. Same with `autoAcceptRequests` under `mediation` key. Or do you think it is valuable to keep it explicit?

**Comment by TimoGlastra** [comment]
We now have modules that configure different parts of the framework. Please open a new issue if other improvement are needed
